spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0