spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/categories/**
            - Path=/products/**
            - Path=/product-images/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0