spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hello_ms_customers
      username: admin
      password: mongoadm
      authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: customer-service
            client-secret: hu4rvwyZC2CKWKjuS4QE9rH2n0jcAQaw
        provider:
          keycloak:
            base-uri: http://localhost:8181/realms/hello-microservice/protocol/openid-connect
            token-uri: ${spring.security.oauth2.client.provider.keycloak.base-uri}/token
            jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.base-uri}/certs

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.addy.customerservice: DEBUG