spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hello_ms_orders
    username: postgres
    password: sqladm
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/hello-microservice
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          customer-service:
            authorization-grant-type: client_credentials
            client-id: customer-service
            client-secret: hu4rvwyZC2CKWKjuS4QE9rH2n0jcAQaw
          product-service:
            authorization-grant-type: client_credentials
            client-id: product-service
            client-secret: 0NLS8ksADbkFbSMn75CcDytdWcwIzVFt
        provider:
          customer-service:
            token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
          product-service:
            token-uri: ${spring.security.oauth2.client.provider.customer-service.token-uri}

server:
  port: 8083

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.addy.orderservice: DEBUG
  logstash:
    enabled: true
    host: localhost
    port: 5044
    queueSize: 512
    customFields: '{"product":"hello-microservice","module":"order-service"}'
  logback:
    appenders:
      logstash:
        type: net.logstash.logback.appender.LogstashTcpSocketAppender
        name: LOGSTASH
        destination: ${logging.logstash.host}:${logging.logstash.port}
        encoder:
          type: net.logstash.logback.encoder.LogstashEncoder
          customFields: ${logging.logstash.customFields}
        queueSize: ${logging.logstash.queueSize}

kafka:
  topic:
    notifications: hello-ms-notifications

mail:
  from: no-reply@addy.org